//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailEntryForm
    {
        public int ID { get; set; }
        public string EmailAddress { get; set; }
        public string CCAddress { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> DepartmentID { get; set; }
        public Nullable<short> LocationID1 { get; set; }
        public Nullable<bool> ReportDateCurrent { get; set; }
        public Nullable<short> LocationID2 { get; set; }
        public Nullable<short> LocationID3 { get; set; }
    }
}
