//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPollData
    {
        public int EmpID { get; set; }
        public string CardNo { get; set; }
        public System.DateTime EntDate { get; set; }
        public System.DateTime EntTime { get; set; }
        public string RdrName { get; set; }
        public short RdrID { get; set; }
        public Nullable<byte> RdrDuty { get; set; }
        public string DeptName { get; set; }
        public string DesignationName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string NicNo { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
    }
}
