//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPayrollData
    {
        public string EmpMonthYear { get; set; }
        public string MonthYear { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EmpNo { get; set; }
        public Nullable<short> TotalDays { get; set; }
        public Nullable<short> EarnedDays { get; set; }
        public Nullable<short> RestDays { get; set; }
        public Nullable<short> AbsentDays { get; set; }
        public Nullable<short> AnnualLeaveDays { get; set; }
        public Nullable<short> SickLeaveDays { get; set; }
        public Nullable<short> CasualDays { get; set; }
        public Nullable<short> OtherLeaveDays { get; set; }
        public Nullable<short> LateInMins { get; set; }
        public Nullable<short> OverTimeMins { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> AnnualLVEncashmentDays { get; set; }
        public string BadliPNo { get; set; }
        public Nullable<short> BadliCompanyID { get; set; }
        public Nullable<short> BadliDays { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> PreparedDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<bool> TransferedToOracle { get; set; }
        public Nullable<System.DateTime> TransferedDate { get; set; }
        public Nullable<int> ApprovedUser { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> FpID { get; set; }
        public string FatherName { get; set; }
        public string NicNo { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remarks { get; set; }
        public string SectionName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> CityID { get; set; }
        public short DeptID { get; set; }
        public string DeptName { get; set; }
        public short DivID { get; set; }
    }
}
